#version: "3.8"

services:
  app:
    build: .
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - .:/usr/src/app
    command: [ "--reload" ]
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"